spring:
  profiles:
    active: dev
---
spring:
  profiles:
    active: div
  application:
    name: microservicecloud-config-atguigu-dev
---
spring:
  profiles:
    active: test
  application:
    name: microservicecloud-config-atguigu-test
#请保存utf-8格式